#!/usr/bin/env php
<?php

require 'bootstrap/autoload.php';

$app = require_once 'bootstrap/app.php';

use Composite\DB\Commands\GenerateEntityCommand;
use Composite\DB\Commands\GenerateTableCommand;
use HaydenPierce\ClassFinder\ClassFinder;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Style\SymfonyStyle;

$commands = [
    new GenerateEntityCommand(),
    new GenerateTableCommand(),
];

$consoleApplication = new Application();
$consoleInput = new ArgvInput();
$consoleOutput = new SymfonyStyle($consoleInput, new ConsoleOutput());


ClassFinder::setAppRoot(ROOT);
try {
    $classesInCommandsNamespace = ClassFinder::getClassesInNamespace(
        'App\\Commands',
        ClassFinder::RECURSIVE_MODE
    );

    $commandClasses = array_filter(
        $classesInCommandsNamespace,
        fn(string $classInCommandNamespace): bool => is_subclass_of($classInCommandNamespace, Command::class)
            && !(new ReflectionClass($classInCommandNamespace))->isAbstract()
    );

    $commandObjects = array_map(
        fn(string $commandClass): Command => $app->getContainer()->get($commandClass),
        $commandClasses,
    );

    $commands = [...$commandObjects, ...$commands];
} catch (Exception $e) {
    $consoleApplication->renderThrowable($e, $consoleOutput);
}


$consoleApplication->addCommands($commands);
$consoleApplication->setCatchExceptions(true);

try {
    $consoleApplication->run($consoleInput, $consoleOutput);
} catch (Throwable $throwable) {
    $consoleApplication->renderThrowable($throwable, $consoleOutput);
}